require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe GigRequestsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # GigRequest. As you add validations to GigRequest, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
   {name: "Jahn Smith", address: "111 Juniper Dr", phone: "999-999-9999", email: "john.smith69@gmail.com", gig_date: "2018-01-01", gig_time: "2000-01-01 08:30:00", gig_duration: 3}
  }

  let(:invalid_attributes) {
    {name: "Jahn Smith"}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GigRequestsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all gig_requests as @gig_requests" do
      gig_request = GigRequest.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:gig_requests)).to eq(@gig_request)
    end
  end

  describe "GET #show" do
    it "assigns the requested gig_request as @gig_request" do
      gig_request = GigRequest.create! valid_attributes
      get :show, {:id => gig_request.to_param}, valid_session
      expect(assigns(:gig_request)).to eq(gig_request)
    end
  end

  describe "GET #new" do
    it "assigns a new gig_request as @gig_request" do
      get :new, {}, valid_session
      expect(assigns(:gig_request)).to be_a_new(GigRequest)
    end
  end

  describe "GET #edit" do
    it "assigns the requested gig_request as @gig_request" do
      gig_request = GigRequest.create! valid_attributes
      get :edit, {:id => gig_request.to_param}, valid_session
      expect(assigns(:gig_request)).to eq(gig_request)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new GigRequest" do
        expect {
          post :create, {:gig_request => valid_attributes}, valid_session
        }.to change(GigRequest, :count).by(1)
      end

      it "assigns a newly created gig_request as @gig_request" do
        post :create, {:gig_request => valid_attributes}, valid_session
        expect(assigns(:gig_request)).to be_a(GigRequest)
        expect(assigns(:gig_request)).to be_persisted
      end

      it "redirects to the created gig_request" do
        post :create, {:gig_request => valid_attributes}, valid_session
        expect(response).to redirect_to(GigRequest.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved gig_request as @gig_request" do
        post :create, {:gig_request => invalid_attributes}, valid_session
        expect(assigns(:gig_request)).to be_a_new(GigRequest)
      end

      it "re-renders the 'new' template" do
        post :create, {:gig_request => invalid_attributes}, valid_session
        expect(response).to render_template("index")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {name: "Jana", address: "121 Juniper Dr", phone: "929-999-9999", email: "jana777@gmail.com", gig_date: "2018-02-01", gig_time: "2000-01-01 08:31:00", gig_duration: 2}
      }

      it "updates the requested gig_request" do
        gig_request = GigRequest.create! valid_attributes
        put :update, {:id => gig_request.to_param, :gig_request => new_attributes}, valid_session
        gig_request.reload
        expect(assigns(:gig_request).attributes['name']).to match(new_attributes[:name])
      end

      it "assigns the requested gig_request as @gig_request" do
        gig_request = GigRequest.create! valid_attributes
        put :update, {:id => gig_request.to_param, :gig_request => valid_attributes}, valid_session
        expect(assigns(:gig_request)).to eq(gig_request)
      end

      it "redirects to the gig_request" do
        gig_request = GigRequest.create! valid_attributes
        put :update, {:id => gig_request.to_param, :gig_request => valid_attributes}, valid_session
        expect(response).to redirect_to(gig_request)
      end
    end

    context "with invalid params" do
      it "assigns the gig_request as @gig_request" do
        gig_request = GigRequest.create! valid_attributes
        put :update, {:id => gig_request.to_param, :gig_request => invalid_attributes}, valid_session
        expect(assigns(:gig_request)).to eq(gig_request)
      end

      it "re-renders the 'edit' template" do
        gig_request = GigRequest.create! valid_attributes
        put :update, {:id => gig_request.to_param, :gig_request => invalid_attributes}, valid_session
        expect(response).to render_template("form")
      end
    end
  end
#response.should render_template(:index)
  describe "DELETE #destroy" do
    it "destroys the requested gig_request" do
      gig_request = GigRequest.create! valid_attributes
      expect {
        delete :destroy, {:id => gig_request.to_param}, valid_session
      }.to change(GigRequest, :count).by(-1)
    end

    it "redirects to the gig_requests list" do
      gig_request = GigRequest.create! valid_attributes
      delete :destroy, {:id => gig_request.to_param}, valid_session
      expect(response).to redirect_to(gig_requests_url)
    end
  end

end
